function [ signal, time ] = generate_baseband( bits, waveform, ...
                            numbitperiods, period, samples_per_bit )
%GENERATEBASEBAND Make a baseband signal from a pulse and bitstream
%   
    adj_period = samples_per_bit; 
    % Subtract one because we only add extra periods after the first bit.
    time = linspace(-numbitperiods/2*period, numbitperiods/2*period + ...
                        (length(bits) - 1)*period,  ...
                        length(waveform) + samples_per_bit*(length(bits) - 1));
    signal = zeros(1,length(time));
    for i = 1:length(bits)
        signal(adj_period * (i-1) + 1: ... 
            adj_period  * (i-1) + ...
            samples_per_bit*numbitperiods) = ...
            signal(adj_period * (i-1) + 1: ... 
            adj_period  * (i-1) + ...
            samples_per_bit*numbitperiods) + (bits(i).* waveform);
    end

end

